// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"context"
)

type Querier interface {
	GetSystemMetadata(ctx context.Context, key string) (SystemMetadatum, error)
	UpsertSystemMetadata(ctx context.Context, arg UpsertSystemMetadataParams) (SystemMetadatum, error)
}

var _ Querier = (*Queries)(nil)
