// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_metadata.sql

package dbsql

import (
	"context"
)

const getSystemMetadata = `-- name: GetSystemMetadata :one
SELECT key, value, updated_at
FROM system_metadata
WHERE key = $1
`

func (q *Queries) GetSystemMetadata(ctx context.Context, key string) (SystemMetadatum, error) {
	row := q.db.QueryRow(ctx, getSystemMetadata, key)
	var i SystemMetadatum
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertSystemMetadata = `-- name: UpsertSystemMetadata :one
INSERT INTO system_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key)
DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
RETURNING key, value, updated_at
`

type UpsertSystemMetadataParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSystemMetadata(ctx context.Context, arg UpsertSystemMetadataParams) (SystemMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertSystemMetadata, arg.Key, arg.Value)
	var i SystemMetadatum
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
